### ISSUE TITLE
gag won't compile with tempfile 2.0.0

### ISSUE THREAD

**Issue by svip** [Stebalien/gag-rs#2]
`tempfile` was *just* upgraded to 2.0.0.[0]  The version of `gag` in crates.io still contains the old `tempfile = "*"` line in its Cargo.toml file, so it attempts to compile with the version of `tempfile`, that it is incompatible with.

Please push a new version of gag to crates.io.

[0] https://crates.io/crates/tempfile/

**Comment by Stebalien** [comment]
As the maintainer of tempfile...
