### ISSUE TITLE
Project Status & Windows Support?

### ISSUE THREAD

**Issue by TheDan64** [Stebalien/gag-rs#3]
Hi, this crate is really useful for FFI tests but I'm hesitant to use it without Windows support. I was wondering if this project is abandoned or if there is a chance the windows branch will be completed at some point?

**Comment by Stebalien** [comment]
Unfortunately, I'm rather busy at the moment. Worse, I don't actually use windows so developing for windows is a bit difficult and a low priority. So, for now, I'm going to have to give you the dreaded "patches welcome" answer.

**Comment by TheDan64** [comment]
Thanks for the reply! Totally understandable. I don't have much windows dev experience but I'd be willing to give it a shot. At the very least, would you be able to give some pointers on what still needs to be implemented based on the current state of your windows branch? That could prove to be very helpful.

**Comment by Stebalien** [comment]
IIRC, I stopped working on it because something simply didn't work when it should have and I couldn't debug it. However, that was a *long* time ago and, at this point, I can't remember any of the details.

**Comment by Stebalien** [comment]
This has now been implemented on windows thanks to @robinbernon (#7).
